version: "3.7"

services:
  next-js:
    container_name: next-server
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    networks:
      - frontend
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    container_name: mongodb
    image: mongo:7.0.1
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=aureus
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend

  flask:
    container_name: flask-api
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - BACKEND_HOST=flask
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME="admin"
      - MONGODB_PASSWORD="password"
    volumes:
      - ./flask:/app
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
