import { Inter } from "next/font/google";
import "@/app/globals.css";
import { AuthProvider, ThemesProvider } from "@/components/providers";

export const metadata = {
  title: "Login - Aureus",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen w-screen grid justify-center items-center bg-background`}
      >
        <ThemesProvider
          attribute="class"
          defaultTheme="system"
          themes={["light", "dark", "system"]}
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
        </ThemesProvider>
      </body>
    </html>
  );
}
